### ISSUE TITLE
Loading collider_without_bb

### ISSUE THREAD

**Issue by pbelange** [ColasDroin/simulation-dashboard#2]
Getting the following error because the .pop method modifies the collider_dict object during the first `Multiline` import
```python
Traceback (most recent call last):
  File "/Users/pbelanger/ABPLocal/BBStudies/Executables/py-COLAS/simulation-dashboard/dashboard.py", line 32, in <module>
    dic_without_bb, dic_with_bb, initial_pickle_path = init.init_from_collider(
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pbelanger/ABPLocal/BBStudies/Executables/py-COLAS/simulation-dashboard/init.py", line 67, in init_from_collider
    collider_without_bb = xt.Multiline.from_dict(collider_dict)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pbelanger/ABPLocal/BBStudies/Executables/miniforge3/envs/py-COLAS/lib/python3.12/site-packages/xtrack/multiline/multiline.py", line 105, in from_dict
    lines[nn] = xt.Line.from_dict(ll)
                ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pbelanger/ABPLocal/BBStudies/Executables/miniforge3/envs/py-COLAS/lib/python3.12/site-packages/xtrack/line.py", line 203, in from_dict
    self.compound_container = CompoundContainer.from_dict(compounds)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pbelanger/ABPLocal/BBStudies/Executables/miniforge3/envs/py-COLAS/lib/python3.12/site-packages/xtrack/compounds.py", line 196, in from_dict
    class_name = ccdd.pop('__class__')
                 ^^^^^^^^^^^^^^^^^^^^^
KeyError: '__class__'
```

Quick fix is to reload the collider_dict variable (copying it the first time did not solve the issue, maybe deepcopy would)

```python
        with open(path_collider, "r") as fid:
            collider_dict = json.load(fid)
        if "config_yaml" in collider_dict:
            print("A configuration has been found in the collider file. Using it.")
            config = collider_dict["config_yaml"]["config_collider"]
        else:
            print(
                "Warning, you provided a collider file without a configuration. Some features of"
                " the dashboard will be missing."
            )
            config = None
        collider = xt.Multiline.from_dict(collider_dict)
        collider.build_trackers()

        # Build collider before bb
        print('Building collider without beam-beam.')
        with open(path_collider, "r") as fid:
            collider_dict = json.load(fid)
        if "config_yaml" in collider_dict:
            print("A configuration has been found in the collider file. Using it.")
            config = collider_dict["config_yaml"]["config_collider"]
        else:
            print(
                "Warning, you provided a collider file without a configuration. Some features of"
                " the dashboard will be missing."
            )
            config = None
        collider_without_bb = xt.Multiline.from_dict(collider_dict)
        collider_without_bb.build_trackers()
        collider_without_bb.vars["beambeam_scale"] = 0
```

**Comment by ColasDroin** [comment]
Thanks for signalling, this problem is due to a recent update of Xmask. I fixed it with a deepcopy to avoid the (lengthy) reload of  collider_dict.
